# This is a basic workflow to help you get started with Actions

name: Deploying to development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Moving config data
      run: |
        mv config.template.json config.json
        sed -i 's|__SERVICE_NAME__|postgres://smg_app_arms:Password03!@35.247.146.32:5432/SMG_DEV|g' config.json

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: taqiprojekan
        password: jimbaran1
        repository: taqiprojekan/dibersihin-backend-dev
        tags: latest
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: taqi20@45.77.39.186
        password: kopigulabatu
        script: ssh deploy.sh




