name: Deploying to development

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploying to VPS
      uses: fifsky/ssh-action@v0.0.4
      with:
        command: sh deploy.sh && exit 0 &&
        host: 45.77.39.186
        user: taqi20
        pass: kopigulabatu
        args: "-tt"
